export const FINANCE_ROUTE_NAMES = {
    // Lookup & Audit
    AUDIT_INDEX: 'finance.audit.index',
    CHARGES_INDEX: 'finance.charges.index',
    CHARGES_SHOW: 'finance.charges.show',
    INVOICES_INDEX: 'finance.invoices.index',
    INVOICES_SHOW: 'finance.invoices.show',
    // Pricing Operations (obligation v2 wave 1)
    PRICING_OPERATIONS_INDEX: 'finance.pricing-operations.index',
    PRICING_OPERATIONS_STORE: 'finance.pricing-operations.store',
    PRICING_OPERATIONS_ACTIVATE: 'finance.pricing-operations.activate',
    PRICING_OPERATIONS_DEACTIVATE: 'finance.pricing-operations.deactivate',

    // Today
    OPERATIONS_DASHBOARD: 'finance.operations.dashboard',
    COCKPIT_INDEX: 'finance.cockpit.index',
    COCKPIT_QUEUE_ROWS: 'finance.cockpit.queue-rows',
    COCKPIT_PHASE: 'finance.cockpit.phase',
    REPORTING_INDEX: 'finance.reporting.index',
    // Fee generation
    MAJOR_CHARGES_INDEX: 'finance.major.charges.index',
    OPERATIONS_GENERATE_CHARGES: 'finance.operations.generate-charges',
    EGC_CHARGES_INDEX: 'finance.egc.charges.index',
    EGC_BLOCK_RESULTS_INDEX: 'finance.egc.block-results.index',
    EGC_RETAKE_ADJUSTMENTS_INDEX: 'finance.egc.retake-adjustments.index',
    EGC_CARRY_FORWARD_INDEX: 'finance.egc.carry-forward.index',
    // Collect & reconcile
    DNG_WORKLIST: 'finance.operations.dng-worklist',
    DNG_PAYMENT_REQUESTS_INDEX: 'finance.dng.payment-requests.index',
    DNG_PAYMENT_REQUESTS_SHOW: 'finance.dng.payment-requests.show',
    DNG_WEBHOOK_EVENTS_INDEX: 'finance.dng.webhook-events.index',
    DNG_WEBHOOK_EVENTS_SHOW: 'finance.dng.webhook-events.show',
    SETTLEMENT_INDEX: 'finance.operations.settlement.index',
    PAYMENTS_INDEX: 'finance.payments.index',
    PAYMENTS_SHOW: 'finance.payments.show',
    DUE_CALENDAR: 'finance.operations.due-calendar',
    // Exceptions
    OPERATIONS_EXCEPTIONS: 'finance.operations.exceptions',
    LIFECYCLE_EXCEPTIONS: 'finance.operations.lifecycle-exceptions',
    LIFECYCLE_EXCEPTION_HISTORY: 'finance.operations.lifecycle-exception-history',
    // New in this milestone
    STUDENT_OVERVIEW: 'finance.students.overview',
    GLOBAL_SEARCH: 'finance.search',
    SEMESTER_CONTEXT_UPDATE: 'finance.semester-context.update',
    PAYMENT_ALLOCATE_PREVIEW: 'finance.payments.allocate-preview',
    PAYMENT_SURPLUS_DISPOSE: 'finance.payments.surplus-dispositions.store',
    PAYMENT_ALLOCATE: 'finance.payments.allocate',
    STUDENT_PAYMENT_STORE: 'finance.students.payments.store',
    DNG_CANCEL_IMPACT: 'finance.dng.payment-requests.cancel-impact',
    DNG_CANCEL_REVIEWED: 'finance.dng.payment-requests.cancel-reviewed',
    INSTALLMENT_RETRY_PUSH: 'finance.charges.installments.retry-push',
    // Batch Studio (milestone 4)
    BATCH_STUDIO_HUB: 'finance.batch-studio.hub',
    BATCH_STUDIO_CHARGES: 'finance.batch-studio.charges',
    BATCH_STUDIO_CHARGES_PREVIEW: 'finance.batch-studio.charges.preview',
    BATCH_STUDIO_CHARGES_COMMIT: 'finance.batch-studio.charges.commit',
    BATCH_STUDIO_DNG: 'finance.batch-studio.dng',
    BATCH_STUDIO_DNG_PREVIEW: 'finance.batch-studio.dng.preview',
    BATCH_STUDIO_DNG_COMMIT: 'finance.batch-studio.dng.commit',
    BATCH_STUDIO_REMINDERS: 'finance.batch-studio.reminders',
    BATCH_STUDIO_REMINDERS_PREVIEW: 'finance.batch-studio.reminders.preview',
    BATCH_STUDIO_REMINDERS_COMMIT: 'finance.batch-studio.reminders.commit',
} as const;
