export const ROOM_BOOKING_ROUTE_NAMES = {
    INDEX: 'room-bookings.index',
    CREATE: 'room-bookings.create',
    STORE: 'room-bookings.store',
    AVAILABILITY: 'room-bookings.availability',
    SHOW: 'room-bookings.show',
    EDIT: 'room-bookings.edit',
    UPDATE: 'room-bookings.update',
    DESTROY: 'room-bookings.destroy',
    MY_BOOKINGS: 'room-bookings.my-bookings',
    PENDING: 'room-bookings.pending',
    CALENDAR: 'room-bookings.calendar',
    LOGS: 'room-bookings.logs',
    APPROVE: 'room-bookings.approve',
    REJECT: 'room-bookings.reject',
    CANCEL: 'room-bookings.cancel',
    API_GET_BOOKINGS: 'api.room-bookings.get-bookings',
    API_CHECK_CONFLICTS: 'api.room-bookings.check-conflicts',
    API_PREVIEW_SERIES: 'api.room-bookings.preview-series',
} as const;
